site_name: "Mon site avec MkDocs"

nav:
  - Accueil : index.md
  - MarkDown MkDocs : markdown.md
  - MarkDown Jupyter : MarkDown-Le_BN_pour_rapporter.ipynb
  - Python : python_script.py


theme:
  name: material
  custom_dir: overrides
  font: false
  language: fr
  logo: https://ericecmorlaix.github.io/img/logo.svg
  favicon: https://ericecmorlaix.github.io/img/logo.svg
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Mode clair


markdown_extensions:
  - meta
  - abbr
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format 
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: false
  - toc:
      permalink: ⚓
      toc_depth: 3


plugins:
  - search
  - macros
  - mermaid2
  - mkdocs-jupyter:
      kernel_name: python3
      execute: False
      include_source: True

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:eric.madec@ecmorlaix.fr
      name: Écrire à l'auteur
    - icon: fontawesome/brands/github
      link: https://github.com/ericECmorlaix/monTestGitHubMkDocs
      name: dépôt github
    - icon: fontawesome/solid/university
      link: https://www.ecmorlaix.fr/nos-etablissements/lycee-notre-dame-du-mur/
      name: Lycée Notre Dame du Mur
  
  io_url: https://ericECmorlaix.github.io/monTestGitHubMkDocs
  
copyright:  Sous licence CC BY-NC-SA 4.0

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css